### ISSUE TITLE
Rollup build issue

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperCollateralRenderer#54]
Never seen this one before. On branch `ga-build`

```
{ TypeError: Cannot read property '0' of undefined
    at bundle.generate.then.result (/Users/gavinatkinson/Tlon/PaperCollateralRenderer/node_modules/gulp-better-rollup/index.js:102:31)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  message: 'Cannot read property \'0\' of undefined',
  name: 'TypeError',
  stack: 'TypeError: Cannot read property \'0\' of undefined\n    at bundle.generate.then.result (/Users/gavinatkinson/Tlon/PaperCollateralRenderer/node_modules/gulp-better-rollup/index.js:102:31)\n    at process._tickCallback (internal/process/next_tick.js:178:7)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-better-rollup',
  showProperties: true,
  showStack: false }
```

**Comment by c-johnson** [comment]
I think gulp-better-rollup requires a peer dependency of rollup 1.x installed now. Try this and see if it works:

`npm install rollup@^1 --save-dev`

**Comment by g-a-v-i-n** [comment]
Thanks! Looks like this was it.
